version: "3"

volumes:
  postgres_volume_prod:

services:
  pg-prod:
      image: "postgres:14-alpine3.17"
      env_file:
        - "config/prod/.env"
      ports:
        - "54322:5432"
      volumes:
        - postgres_volume_prod:/val/lib/postgresql/data

  migrator-prod:
    build:
      context: .
      dockerfile: "config/prod/migration.Dockerfile"
    restart: on-failure
    environment:
      DB_HOST: pg-prod

  app:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "50052:50052"
    restart: on-failure

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=0

  prometheus:
    image: prom/prometheus:v2.37.9
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yml
      - prometheus_data:/prometheus
    network_mode: "host"

  grafana:
    image: grafana/grafana-oss:10.0.3
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    network_mode: "host"

  jaeger:
    image: jaegertracing/all-in-one:1.48
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686" # web
      - "14268:14268"
      - "9411:9411"